header:
  version: 14

machine: raspberrypi4-64
distro: poky

defaults:
  repos:
    branch: scarthgap

repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    path: layers/poky
    layers:
      meta:
      meta-poky:
  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    path: layers/meta-openembedded
    layers:
      meta-oe:
      meta-python:
  meta-raspberrypi:
    url: "https://github.com/agherzan/meta-raspberrypi"
    path: layers/meta-raspberrypi
  meta-rauc:
    url: "https://github.com/rauc/meta-rauc.git"
    path: layers/meta-rauc
  meta-rauc-community:
    url: "https://github.com/rauc/meta-rauc-community"
    path: layers/meta-rauc-community
    layers:
      meta-rauc-raspberrypi:

  elepi:
    layers:
      layers/meta-elepi-base:
      layers/meta-elepi-userspace-odyssey:

target:
  - core-image-minimal
  #- update-bundle

local_conf_header:
  meta-custom: |
    # GENERAL
    # ---
    PACKAGE_CLASSES = "package_rpm"

    # MACHINE
    # ---
    ENABLE_UART = "1"
    RPI_USE_U_BOOT = "1"

    # DISTRO
    # ---
    DISTRO_FEATURES:append = " rauc overlayfs"
    INIT_MANAGER = "systemd"

    # IMAGE
    # ---
    IMAGE_INSTALL:append = " rauc"
    IMAGE_FSTYPES:append = " ext4"
    
    EXTRA_IMAGE_FEATURES += "debug-tweaks"
    EXTRA_IMAGE_FEATURES += "ssh-server-openssh"

    # Overlay for writable application paths
    OVERLAYFS_MOUNT_POINT[data] = "/data"