header:
  version: 14

distro: poky

defaults:
  repos:
    branch: styhead
repos:
  # Shared layers
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    path: layers/poky
    layers:
      meta:
      meta-poky:
  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded"
    path: layers/meta-openembedded
    layers:
      meta-oe:
      meta-python:
  meta-rauc:
    url: "https://github.com/rauc/meta-rauc.git"
    path: layers/meta-rauc

  elepi:
    layers:
      layers/meta-elepi-base:
      layers/meta-elepi-userspace-odyssey:

target:
  - core-image-minimal
  #- update-bundle

local_conf_header:
  elepi-common: |
    # GENERAL
    # ---
    PACKAGE_CLASSES = "package_rpm"

    hostname:pn-base-files = "elepi"
    DISTRO_NAME:pn-base-files = "elepi-adventure"
    DISTRO_VERSION:pn-base-files = "0.1-beta"

    # DISTRO
    # ---
    DISTRO_FEATURES:append = " rauc overlayfs"
    INIT_MANAGER = "systemd"

    # IMAGE
    # ---
    OVERLAYFS_MOUNT_POINT[data] = "/data"